### PR TITLE
Adds support for FasterWhisper

### PR DESCRIPTION
**Pull request by alienware**
# WHAT
- Install `faster_whisper` package side-by-side
- Adds `faster` boolean parameter to `transcribe` and `detect-language` APIs to switch between models at request time
- Adds `utils` for `faster_whisper` module to support `whisper` style helpers

# WHY
- #78 #79 

# CHANGELOG
- Adds docker compose support
- Better poetry cache handling in Dockerfile
- Whisper model download and conversion for faster_whisper is done at docker image build stage

### CODE REVIEW

**Comment by ayancey** [comment]
Really looking forward to this!

**Comment by ahmetoner** [comment]
Thanks for your contribution, I will merge it soon.

**Comment by tammo0** [comment]
Hi! Thanks for your work!

I builded a docker with alienware's repo on windows 11 and had some troubles.
But finally it worked when you follow the information from #83 and change line 21 of Dockerfile.gpu to `&& $POETRY_VENV/bin/pip install "poetry==1.4.0"` and keep an eye on the line endings of the faster_whisper_model_converstion.sh because it doesn't get executed at windows right now. Adding this to line 40 did the trick for me:

> RUN sed -i 's/\r$//' faster_whisper_model_conversion.sh  && \  
        chmod +x faster_whisper_model_conversion.sh

**Comment by tarjei** [comment]
Hi, I tried out this PR but got the error:

RuntimeError: Unable to open file 'model.bin' in model '/root/.cache/faster_whisper'

after running `podman build -t fast-whisper .` && `podman run  -d -p 9000:9000 -e ASR_MODEL=large-v2 localhost/fast-whisper`

**Comment by tarjei** [comment]
Update. I got around this issue by adding this to the Dockerfile: 

```diff
+ENV ASR_MODEL="large-v2"
+
+# TODO: Skip based on ENV variable
+RUN ./faster_whisper_model_conversion.sh ${ASR_MODEL}
```

But after starting the container, there is no response on port 9000 nor any errors in the logs. Any tips on where to debug this?

**Comment by alienware** [comment]
@tarjei My guess with be to use `podman logs` command to check the pod logs.

**Comment by jordimas** [comment]
You may also consider using https://pypi.org/project/whisper-ctranslate2/

**Comment by blundercode** [comment]
Would love support for faster whisper!

**Review by ahmetoner — APPROVED** [review]

**Comment by ahmetoner** [comment]
I will have some changes on ahmetoner:faster-whisper. After finish, I will merge it with main branch.

**Pull request merged**
